### Variáveis de ambiente
@base_url = http://127.0.0.1:8000

### USUARIOS
POST {{base_url}}/usuario
Content-Type: application/json

{
  "nome": "Davi Joaquim",
  "cpf": "47066052889",
  "data_nascimento": "2009-06-01",
  "senha": "12345",
  "email": "davi@gmail.com",
  "usuario": "davizao"
}

### PASSAGEIROS
POST {{base_url}}/passageiro
Content-Type: application/json

{
  "id_usuario": 1,
  "id_passageiro": 2,
  "media_avaliacao": 4
}

### MOTORISTAS
POST {{base_url}}/motorista
Content-Type: application/json

{
  "id_usuario": 1,
  "nome_motorista": "Davi",
  "media_avaliacao": 4,
  "cnh": "12345678901"
}

### TIPO COMBUSTIVEL
POST {{base_url}}/tipo_combustivel
Content-Type: application/json

{
  "descricao": "Alcool",
  "fator_carbono": 1.0
}

### MODELO VEICULO
POST {{base_url}}/modelo_veiculo
Content-Type: application/json

{
  "id_modelo_veiculo": 1,
  "id_veiculo": 1,
  "id_motorista": 1,
  "id_tipo_combustivel": 1,
  "modelo": "Onix",
  "marca": "Chevrolet",
  "placa": "ABC5627",
  "cor": "Cinza",
  "ano": 2023,
  "propriedade": "Proprio",
  "capacidade": 5

}

### CLASSE VEICULO
POST {{base_url}}/classe
Content-Type: application/json

{
  "nome_classe": "Uber Comfort",
  "fator_preco": 1.0
}
###

### VEICULO
POST {{base_url}}/veiculo
Content-Type: application/json

{
    "id_veiculo": 1, 
    "id_modelo_veiculo": 1,  
    "tem_seguro": true,
    "id_classe": 1,
    "placa":  "ABC3454"
}
###

