### Variáveis de ambiente
@base_url = http://127.0.0.1:8000

### USUARIOS
POST {{base_url}}/usuario
Content-Type: application/json

{
  "nome": "Filipe Polycarpo",
  "cpf": "12345678901",
  "data_nascimento": "2000-09-15",
  "senha": "123",
  "email": "filipe@gmail.com",
  "username": "filipe"
}
###

POST http://127.0.0.1:8000/usuarios
Content-Type: application/json

{
  "nome": "Fernanda Cardozo",
  "cpf": "98765432100",
  "data_nascimento": "1998-10-25",
  "senha": "123",
  "email": "fernanda@gmail.com",
  "username": "fernanda"
}
###

POST http://127.0.0.1:8000/usuarios
Content-Type: application/json

{
  "nome": "Miriã Jesus",
  "cpf": "98765432867",
  "data_nascimento": "2037-12-17",
  "senha": "123",
  "email": "miria.jesus@gmail.com",
  "username": "Miriã"
}
###

### PASSAGEIROS
POST http://127.0.0.1:8000/Passageiros/
Content-Type: application/json

{
  "id_usuario": 1,
  "nome_passageiro": "Filipe",
  "media_avaliacao": 4.7
}
###

POST http://127.0.0.1:8000/Passageiros/
Content-Type: application/json

{
  "id_usuario": 9,
  "nome_passageiro": "Miriã",
  "media_avaliacao": 5.0
}
###

### MOTORISTAS
POST http://127.0.0.1:8000/motoristas
Content-Type: application/json

{
  "id_usuario": 6,
  "nome_motorista": "Fernanda",
  "media_avaliacao": 4.9,
  "cnh": "12345678901"
}
###

### TIPO COMBUSTIVEL
POST http://127.0.0.1:8000/tipos-combustivel
Content-Type: application/json

{
  "descricao": "Gasolina",
  "fator_carbono": 2.3
}
###

### MODELO VEICULO
POST http://127.0.0.1:8000/modelos-veiculo
Content-Type: application/json

{
  "nome_modelo": "HB20",
  "fabricante": "Hyundai",
  "cor": "Branco",
  "ano": 2020,
  "capacidade": 4,
  "propriedade": "Proprio",
  "id_tipo_combustivel": 1
}
###

### CLASSE VEICULO
POST http://127.0.0.1:8000/classes-veiculo
Content-Type: application/json

{
  "nome_classe": "UberX",
  "fator_preco": 1.0
}
###

### VEICULO
POST http://127.0.0.1:8000/veiculos
Content-Type: application/json

{
  "placa_veiculo": "ABC1234",
  "id_modelo_veiculo": 1,
  "tem_seguro": true,
  "id_classe_veiculo": 1
}
###

### MOTORISTA_VEICULO
POST http://127.0.0.1:8000/motorista-veiculo
Content-Type: application/json

{
  "id_motorista": 1,
  "id_veiculo": 1,
  "datahora_inicio_disponibilidade": "2025-02-10T08:00:00",
  "datahora_fim_disponibilidade": "2025-02-10T18:00:00"
}
###

### METODO PAGAMENTO
POST http://127.0.0.1:8000/metodos-pagamento
Content-Type: application/json

{
  "descricao": "Pix",
  "nome_financeira": "Todos"
}
###

### SERVICO
POST http://127.0.0.1:8000/servicos
Content-Type: application/json

{
  "nome_servico": "Corrida",
  "id_classe_minima": 1
}
###

### AVALIACAO
POST http://127.0.0.1:8000/avaliacoes
Content-Type: application/json

{
  "nota_passageiro": 4.5,
  "nota_motorista": 4.8,
  "datahora_limite": "2025-02-10T18:30:00"
}
###

### CORRIDA
POST http://127.0.0.1:8000/corridas
Content-Type: application/json

{
  "id_passageiro": 1,
  "id_motorista": 1,
  "id_servico": 1,
  "id_avaliacao": 1,
  "datahora_inicio": "2025-01-10T08:15:00",
  "datahora_fim": "2025-01-10T08:30:00",
  "duracao_total": 15,
  "gps_partida": "A",
  "gps_destino": "B",
  "valor_estimado": 20,
  "status": "finalizada"
}
###

### PAGAMENTO
POST http://127.0.0.1:8000/pagamentos
Content-Type: application/json

{
  "id_corrida": 1,
  "valor": 20,
  "id_metodo_pagamento": 1,
  "datahora_transacao": "2025-01-10T08:35:00"
}
###










-